const {test}=require('node:test');
const assert=require('node:assert/strict'); const fs=require('node:fs'); const vm=require('node:vm');
const source=fs.readFileSync('assets/js/app.js','utf8');
const helpers=source.slice(source.indexOf('function notificationTarget('),source.indexOf('window.applyFilters = function()'));
const id='12345678-1234-1234-1234-123456789abc';
function setup(order,search='?order='+id){const card={dataset:{orderId:id},classList:{add:()=>{}},scrollIntoView:()=>{}};const inputs={searchInput:{value:'hidden'},filterService:{value:'topup'}};const calls=[]; const c={URLSearchParams,currentUser:{id:'actor'},allOrders:order?[order]:[],alert:m=>calls.push(m),document:{getElementById:k=>inputs[k],querySelectorAll:()=>[card]},window:{location:{search},filterByTab:t=>calls.push(t),openChat:async (...args)=>calls.push(args)}};vm.createContext(c);vm.runInContext(helpers,c);return {c,calls,inputs};}
test('order and chat targets use safe internal links',()=>{const {c}=setup();assert.equal(c.notificationTarget({order_id:id}),'/dashboard?order='+id);assert.equal(c.notificationTarget({order_id:id,title:'Tin nhắn mới'}),'/dashboard?order='+id+'&section=chat');assert.equal(c.notificationTarget({order_id:'javascript:alert(1)'}),'/dashboard');assert.equal(c.notificationTarget({title:'Yêu cầu hỗ trợ được cập nhật'}),'/dashboard?section=support');});
test('cancelled destination clears filters and opens chat only once',async()=>{const {c,calls,inputs}=setup({id,cancelled:true,order_code:'NC001'},'?order='+id+'&section=chat');await c.window.openNotificationDestination();await c.window.openNotificationDestination();assert.equal(inputs.searchInput.value,'');assert.equal(inputs.filterService.value,'all');assert.equal(calls[0],'cancelled');assert.deepEqual(Array.from(calls[1]),[id,'NC001']);assert.equal(calls.length,2);});
test('active order opens all tab; missing order gives explanation',async()=>{const active=setup({id,cancelled:false});await active.c.window.openNotificationDestination();assert.equal(active.calls[0],'all');const missing=setup(null);await missing.c.window.openNotificationDestination();assert.match(missing.calls[0],/không có quyền/);});
test('notifications render native links and scope read updates to current actor',()=>{assert.match(source,/data-notification-id=/);assert.match(source,/eq\('id', link.dataset.notificationId\)\.eq\('user_id', actor\)/);assert.match(source,/currentUser\?\.id !== currentUserId/);assert.match(source,/ticket.response/);});

test('support destination renders server response and empty inbox',async()=>{for(const data of [[],[{issue_type:'Sai UID',description:'Xin kiểm tra',response:'Đã xử lý',order_id:id}]]){const h=setup(null,'?section=support');const panel={innerHTML:'',scrollIntoView:()=>{}};h.c.escapeHtml=v=>String(v);h.c.document.getElementById=k=>k==='notificationSupport'?panel:null;h.c.supabaseClient={from:()=>({select:()=>({eq:()=>({order:async()=>({data,error:null})})})})};await h.c.window.openNotificationDestination();assert.match(panel.innerHTML,data.length?/Đã xử lý/:/chưa có yêu cầu/);}});
